repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
- repo: https://github.com/pre-commit/mirrors-black
  rev: v20.8b1
  hooks:
  - id: black
- repo: https://github.com/pre-commit/mirrors-flake8
  rev: v4.0.0
  hooks:
  - id: flake8
