repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3.8
        args:
          - app
  # up containers with docker-compose and run tests
  - repo: local
    hooks:
      - id: docker pytest
        name: docker pytest
        entry: bash -c "cd .docker && docker-compose run app pytest"
        language: system
        pass_filenames: false
        always_run: true
        stages: [commit]
        verbose: true
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.1.1
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
 
