"""

Revision ID: c501bcbbd34c
Revises: 43dbaa513fdc
Create Date: 2023-11-30 01:11:57.706984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c501bcbbd34c'
down_revision: Union[str, None] = '43dbaa513fdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.drop_index('ix_emails_description', table_name='emails')
    op.drop_index('ix_emails_title', table_name='emails')
    op.add_column('events', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'events', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'product_id')
    op.create_index('ix_emails_title', 'emails', ['title'], unique=False)
    op.create_index('ix_emails_description', 'emails', ['description'], unique=False)
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
