version: "3.9"
services:
  app:
    container_name: app
    build:
      context: ../
      dockerfile: .docker/dev.Dockerfile
    image: app
    command: "make start"
    volumes:
      - ../:/src
    ports:
      - "8080:8080"
    restart: "no"
volumes:
  db_volume:
    driver: local



